### PR TITLE
TSC build updates & allow copy of CSS when using produceHtml

### PR DESCRIPTION
**Pull request by b3kN**
TSC build updates.

Allowed functionality to copy CSS & font files when produceHtml is set to true as a capability or reporter setting.

### CODE REVIEW

**Comment by b3kN** [comment]
@rpii , tag

**Comment by rpii** [comment]
can you remove the log messages which say PRODUCE HTML and I will merge

**Comment by b3kN** [comment]
> can you remove the log messages which say PRODUCE HTML and I will merge

I scanned the PR again and I think I removed all of the logs that were pushed initially. I didn't see the PRODUCE HTML log anymore when searching in the source. 

I think the newest commit to the PR should be better.

**Comment by rpii** [comment]
Thanks I will merge it tonight

**Pull request merged**
